# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'motion-splash'
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'sample-2'

  MotionSplash.setup(app) do |c|
    c.controller_class = "CustomSplashViewController"
    c.custom_sizes = [[[667, 375], 2]]
  end
end
